//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_CityMaster
    {
        public int n_CityID { get; set; }
        public string s_CityCode { get; set; }
        public string s_CityDesc { get; set; }
        public System.DateTime d_LastModifiedDateTime { get; set; }
    }
}
