//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ProgramMaster
    {
        public int n_ProgramID { get; set; }
        public string s_Code { get; set; }
        public string s_Desc { get; set; }
        public decimal n_Amount { get; set; }
        public int n_NoOfMonths { get; set; }
        public int n_UserNo { get; set; }
        public System.DateTime d_LastModifiedDateTime { get; set; }
    }
}
